package duckdb

/*
#include <go_duckdb.h>
*/
import "C"

type Type C.duckdb_type

const (
	TYPE_INVALID      Type = C.DUCKDB_TYPE_INVALID
	TYPE_BOOLEAN      Type = C.DUCKDB_TYPE_BOOLEAN
	TYPE_TINYINT      Type = C.DUCKDB_TYPE_TINYINT
	TYPE_SMALLINT     Type = C.DUCKDB_TYPE_SMALLINT
	TYPE_INTEGER      Type = C.DUCKDB_TYPE_INTEGER
	TYPE_BIGINT       Type = C.DUCKDB_TYPE_BIGINT
	TYPE_UTINYINT     Type = C.DUCKDB_TYPE_UTINYINT
	TYPE_USMALLINT    Type = C.DUCKDB_TYPE_USMALLINT
	TYPE_UINTEGER     Type = C.DUCKDB_TYPE_UINTEGER
	TYPE_UBIGINT      Type = C.DUCKDB_TYPE_UBIGINT
	TYPE_FLOAT        Type = C.DUCKDB_TYPE_FLOAT
	TYPE_DOUBLE       Type = C.DUCKDB_TYPE_DOUBLE
	TYPE_TIMESTAMP    Type = C.DUCKDB_TYPE_TIMESTAMP
	TYPE_DATE         Type = C.DUCKDB_TYPE_DATE
	TYPE_TIME         Type = C.DUCKDB_TYPE_TIME
	TYPE_INTERVAL     Type = C.DUCKDB_TYPE_INTERVAL
	TYPE_HUGEINT      Type = C.DUCKDB_TYPE_HUGEINT
	TYPE_UHUGEINT     Type = C.DUCKDB_TYPE_UHUGEINT
	TYPE_VARCHAR      Type = C.DUCKDB_TYPE_VARCHAR
	TYPE_BLOB         Type = C.DUCKDB_TYPE_BLOB
	TYPE_DECIMAL      Type = C.DUCKDB_TYPE_DECIMAL
	TYPE_TIMESTAMP_S  Type = C.DUCKDB_TYPE_TIMESTAMP_S
	TYPE_TIMESTAMP_MS Type = C.DUCKDB_TYPE_TIMESTAMP_MS
	TYPE_TIMESTAMP_NS Type = C.DUCKDB_TYPE_TIMESTAMP_NS
	TYPE_ENUM         Type = C.DUCKDB_TYPE_ENUM
	TYPE_LIST         Type = C.DUCKDB_TYPE_LIST
	TYPE_STRUCT       Type = C.DUCKDB_TYPE_STRUCT
	TYPE_MAP          Type = C.DUCKDB_TYPE_MAP
	TYPE_ARRAY        Type = C.DUCKDB_TYPE_ARRAY
	TYPE_UUID         Type = C.DUCKDB_TYPE_UUID
	TYPE_UNION        Type = C.DUCKDB_TYPE_UNION
	TYPE_BIT          Type = C.DUCKDB_TYPE_BIT
	TYPE_TIME_TZ      Type = C.DUCKDB_TYPE_TIME_TZ
	TYPE_TIMESTAMP_TZ Type = C.DUCKDB_TYPE_TIMESTAMP_TZ
	TYPE_ANY          Type = C.DUCKDB_TYPE_ANY
	TYPE_VARINT       Type = C.DUCKDB_TYPE_VARINT
	TYPE_SQLNULL      Type = C.DUCKDB_TYPE_SQLNULL
)

type State C.duckdb_state

const (
	STATE_SUCCESS State = C.DuckDBSuccess
	STATE_ERROR   State = C.DuckDBError
)

type PendingState C.duckdb_pending_state

const (
	PENDING_RESULT_READY       PendingState = C.DUCKDB_PENDING_RESULT_READY
	PENDING_RESULT_NOT_READY   PendingState = C.DUCKDB_PENDING_RESULT_NOT_READY
	PENDING_ERROR              PendingState = C.DUCKDB_PENDING_ERROR
	PENDING_NO_TASKS_AVAILABLE PendingState = C.DUCKDB_PENDING_NO_TASKS_AVAILABLE
)

type ResultType C.duckdb_result_type

const (
	RESULT_TYPE_INVALID      ResultType = C.DUCKDB_RESULT_TYPE_INVALID
	RESULT_TYPE_CHANGED_ROWS ResultType = C.DUCKDB_RESULT_TYPE_CHANGED_ROWS
	RESULT_TYPE_NOTHING      ResultType = C.DUCKDB_RESULT_TYPE_NOTHING
	RESULT_TYPE_QUERY_RESULT ResultType = C.DUCKDB_RESULT_TYPE_QUERY_RESULT
)

type StatementType C.duckdb_statement_type

const (
	STATEMENT_TYPE_INVALID      StatementType = C.DUCKDB_STATEMENT_TYPE_INVALID
	STATEMENT_TYPE_SELECT       StatementType = C.DUCKDB_STATEMENT_TYPE_SELECT
	STATEMENT_TYPE_INSERT       StatementType = C.DUCKDB_STATEMENT_TYPE_INSERT
	STATEMENT_TYPE_UPDATE       StatementType = C.DUCKDB_STATEMENT_TYPE_UPDATE
	STATEMENT_TYPE_EXPLAIN      StatementType = C.DUCKDB_STATEMENT_TYPE_EXPLAIN
	STATEMENT_TYPE_DELETE       StatementType = C.DUCKDB_STATEMENT_TYPE_DELETE
	STATEMENT_TYPE_PREPARE      StatementType = C.DUCKDB_STATEMENT_TYPE_PREPARE
	STATEMENT_TYPE_CREATE       StatementType = C.DUCKDB_STATEMENT_TYPE_CREATE
	STATEMENT_TYPE_EXECUTE      StatementType = C.DUCKDB_STATEMENT_TYPE_EXECUTE
	STATEMENT_TYPE_ALTER        StatementType = C.DUCKDB_STATEMENT_TYPE_ALTER
	STATEMENT_TYPE_TRANSACTION  StatementType = C.DUCKDB_STATEMENT_TYPE_TRANSACTION
	STATEMENT_TYPE_COPY         StatementType = C.DUCKDB_STATEMENT_TYPE_COPY
	STATEMENT_TYPE_ANALYZE      StatementType = C.DUCKDB_STATEMENT_TYPE_ANALYZE
	STATEMENT_TYPE_VARIABLE_SET StatementType = C.DUCKDB_STATEMENT_TYPE_VARIABLE_SET
	STATEMENT_TYPE_CREATE_FUNC  StatementType = C.DUCKDB_STATEMENT_TYPE_CREATE_FUNC
	STATEMENT_TYPE_DROP         StatementType = C.DUCKDB_STATEMENT_TYPE_DROP
	STATEMENT_TYPE_EXPORT       StatementType = C.DUCKDB_STATEMENT_TYPE_EXPORT
	STATEMENT_TYPE_PRAGMA       StatementType = C.DUCKDB_STATEMENT_TYPE_PRAGMA
	STATEMENT_TYPE_VACUUM       StatementType = C.DUCKDB_STATEMENT_TYPE_VACUUM
	STATEMENT_TYPE_CALL         StatementType = C.DUCKDB_STATEMENT_TYPE_CALL
	STATEMENT_TYPE_SET          StatementType = C.DUCKDB_STATEMENT_TYPE_SET
	STATEMENT_TYPE_LOAD         StatementType = C.DUCKDB_STATEMENT_TYPE_LOAD
	STATEMENT_TYPE_RELATION     StatementType = C.DUCKDB_STATEMENT_TYPE_RELATION
	STATEMENT_TYPE_EXTENSION    StatementType = C.DUCKDB_STATEMENT_TYPE_EXTENSION
	STATEMENT_TYPE_LOGICAL_PLAN StatementType = C.DUCKDB_STATEMENT_TYPE_LOGICAL_PLAN
	STATEMENT_TYPE_ATTACH       StatementType = C.DUCKDB_STATEMENT_TYPE_ATTACH
	STATEMENT_TYPE_DETACH       StatementType = C.DUCKDB_STATEMENT_TYPE_DETACH
	STATEMENT_TYPE_MULTI        StatementType = C.DUCKDB_STATEMENT_TYPE_MULTI
)

type ErrorType C.duckdb_error_type

const (
	ERROR_INVALID                ErrorType = C.DUCKDB_ERROR_INVALID
	ERROR_OUT_OF_RANGE           ErrorType = C.DUCKDB_ERROR_OUT_OF_RANGE
	ERROR_CONVERSION             ErrorType = C.DUCKDB_ERROR_CONVERSION
	ERROR_UNKNOWN_TYPE           ErrorType = C.DUCKDB_ERROR_UNKNOWN_TYPE
	ERROR_DECIMAL                ErrorType = C.DUCKDB_ERROR_DECIMAL
	ERROR_MISMATCH_TYPE          ErrorType = C.DUCKDB_ERROR_MISMATCH_TYPE
	ERROR_DIVIDE_BY_ZERO         ErrorType = C.DUCKDB_ERROR_DIVIDE_BY_ZERO
	ERROR_OBJECT_SIZE            ErrorType = C.DUCKDB_ERROR_OBJECT_SIZE
	ERROR_INVALID_TYPE           ErrorType = C.DUCKDB_ERROR_INVALID_TYPE
	ERROR_SERIALIZATION          ErrorType = C.DUCKDB_ERROR_SERIALIZATION
	ERROR_TRANSACTION            ErrorType = C.DUCKDB_ERROR_TRANSACTION
	ERROR_NOT_IMPLEMENTED        ErrorType = C.DUCKDB_ERROR_NOT_IMPLEMENTED
	ERROR_EXPRESSION             ErrorType = C.DUCKDB_ERROR_EXPRESSION
	ERROR_CATALOG                ErrorType = C.DUCKDB_ERROR_CATALOG
	ERROR_PARSER                 ErrorType = C.DUCKDB_ERROR_PARSER
	ERROR_PLANNER                ErrorType = C.DUCKDB_ERROR_PLANNER
	ERROR_SCHEDULER              ErrorType = C.DUCKDB_ERROR_SCHEDULER
	ERROR_EXECUTOR               ErrorType = C.DUCKDB_ERROR_EXECUTOR
	ERROR_CONSTRAINT             ErrorType = C.DUCKDB_ERROR_CONSTRAINT
	ERROR_INDEX                  ErrorType = C.DUCKDB_ERROR_INDEX
	ERROR_STAT                   ErrorType = C.DUCKDB_ERROR_STAT
	ERROR_CONNECTION             ErrorType = C.DUCKDB_ERROR_CONNECTION
	ERROR_SYNTAX                 ErrorType = C.DUCKDB_ERROR_SYNTAX
	ERROR_SETTINGS               ErrorType = C.DUCKDB_ERROR_SETTINGS
	ERROR_BINDER                 ErrorType = C.DUCKDB_ERROR_BINDER
	ERROR_NETWORK                ErrorType = C.DUCKDB_ERROR_NETWORK
	ERROR_OPTIMIZER              ErrorType = C.DUCKDB_ERROR_OPTIMIZER
	ERROR_NULL_POINTER           ErrorType = C.DUCKDB_ERROR_NULL_POINTER
	ERROR_IO                     ErrorType = C.DUCKDB_ERROR_IO
	ERROR_INTERRUPT              ErrorType = C.DUCKDB_ERROR_INTERRUPT
	ERROR_FATAL                  ErrorType = C.DUCKDB_ERROR_FATAL
	ERROR_INTERNAL               ErrorType = C.DUCKDB_ERROR_INTERNAL
	ERROR_INVALID_INPUT          ErrorType = C.DUCKDB_ERROR_INVALID_INPUT
	ERROR_OUT_OF_MEMORY          ErrorType = C.DUCKDB_ERROR_OUT_OF_MEMORY
	ERROR_PERMISSION             ErrorType = C.DUCKDB_ERROR_PERMISSION
	ERROR_PARAMETER_NOT_RESOLVED ErrorType = C.DUCKDB_ERROR_PARAMETER_NOT_RESOLVED
	ERROR_PARAMETER_NOT_ALLOWED  ErrorType = C.DUCKDB_ERROR_PARAMETER_NOT_ALLOWED
	ERROR_DEPENDENCY             ErrorType = C.DUCKDB_ERROR_DEPENDENCY
	ERROR_HTTP                   ErrorType = C.DUCKDB_ERROR_HTTP
	ERROR_MISSING_EXTENSION      ErrorType = C.DUCKDB_ERROR_MISSING_EXTENSION
	ERROR_AUTOLOAD               ErrorType = C.DUCKDB_ERROR_AUTOLOAD
	ERROR_SEQUENCE               ErrorType = C.DUCKDB_ERROR_SEQUENCE
	INVALID_CONFIGURATION        ErrorType = C.DUCKDB_INVALID_CONFIGURATION
)

type CastMode C.duckdb_cast_mode

const (
	CAST_NORMAL CastMode = C.DUCKDB_CAST_NORMAL
	CAST_TRY    CastMode = C.DUCKDB_CAST_TRY
)
